### ISSUE TITLE
アプリ起動時鍵の状態取得できないときがある。

### ISSUE THREAD

**Issue by takerusakano** [cosmoway/smalo-ios#2]

**Comment by takerusakano** [comment]
アプリ側でうまくweb socketとコネクトできていない可能性がある

**Comment by yuukis** [comment]
たしか @ryujyu さんも困っていたですね。

**Comment by gokazy** [comment]
確かにあるっぽいです。バックグラウンドから起動した場合に多いような…
アプリの不具合なのか、edisonやserverの不具合なのか一瞬わからないのもちょっと辛いところですね〜。
メッセージなりUIなりを工夫したいです。

**Comment by takerusakano** [comment]
上記マージされましたのでDoneに移しました。

**Comment by yuukis** [comment]
@takerusakano ありがとうございました 😄
